/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "testfile.v:1" *)
module mux_2to1(Y, A, B, sel);
  (* src = "testfile.v:10" *)
  wire [1:0] _0_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [1:0] _1_;
  wire [1:0] _2_;
  (* src = "testfile.v:3" *)
  input [1:0] A;
  (* src = "testfile.v:3" *)
  input [1:0] B;
  (* src = "testfile.v:2" *)
  output [1:0] Y;
  (* src = "testfile.v:4" *)
  input sel;
  assign Y[1] = sel ? (* src = "testfile.v:7" *) _0_[1] : _2_[1];
  assign Y[0] = A[0] ^(* src = "<techmap.v>:262" *)  B[0];
  assign _2_[1] = A[1] ^(* src = "<techmap.v>:262" *)  B[1];
  assign _0_[1] = _2_[1] ^(* src = "<techmap.v>:263" *)  _1_[0];
  assign _1_[0] = A[0] &(* src = "<techmap.v>:260" *)  B[0];
endmodule
