/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "testfile_out.v:1" *)
module mux_2to1(Y, A, B, sel);
  (* src = "testfile_out.v:9" *)
  wire _03_;
  (* src = "testfile_out.v:9" *)
  wire _04_;
  (* src = "testfile_out.v:9" *)
  wire _05_;
  (* src = "testfile_out.v:5" *)
  input [1:0] A;
  (* src = "testfile_out.v:6" *)
  input [1:0] B;
  (* src = "testfile_out.v:7" *)
  output [1:0] Y;
  (* src = "testfile_out.v:2" *)
  wire [1:0] _0_;
  (* src = "testfile_out.v:3" *)
  wire [1:0] _1_;
  (* src = "testfile_out.v:4" *)
  wire [1:0] _2_;
  (* src = "testfile_out.v:8" *)
  input sel;
  assign _05_ = ~(* src = "testfile_out.v:9" *) sel;
  assign _03_ = sel &(* src = "testfile_out.v:9" *)  _0_[1];
  assign _04_ = _05_ &(* src = "testfile_out.v:9" *)  _2_[1];
  assign Y[1] = _03_ |(* src = "testfile_out.v:9" *)  _04_;
  assign Y[0] = A[0] ^(* src = "testfile_out.v:10" *)  B[0];
  assign _2_[1] = A[1] ^(* src = "testfile_out.v:11" *)  B[1];
  assign _0_[1] = _2_[1] ^(* src = "testfile_out.v:12" *)  _1_[0];
  assign _1_[0] = A[0] &(* src = "testfile_out.v:13" *)  B[0];
endmodule
