/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */


module mux_2to1(Y, A, B, sel);
  
  wire _03_;
  
  wire _04_;
  
  wire _05_;
  
  wire _06_;
  
  wire _07_;
  
  wire _08_;
  
  wire _09_;
  
  wire _10_;
  
  wire _11_;
  
  wire _12_;
  
  wire _13_;
  
  wire _14_;
  
  wire _15_;
  
  wire _16_;
  
  wire _17_;
  
  input [1:0] A;
  
  input [1:0] B;
  
  output [1:0] Y;
  
  wire [1:0] _0_;
  
  wire [1:0] _1_;
  
  wire [1:0] _2_;
  
  input sel;
  assign _17_ = ~ sel;
  assign _11_ = ~ A[0];
  assign _12_ = ~ B[0];
  assign _13_ = ~ A[1];
  assign _14_ = ~ B[1];
  assign _15_ = ~ _2_[1];
  assign _16_ = ~ _1_[0];
  assign _09_ = sel &  _0_[1];
  assign _10_ = _17_ &  _2_[1];
  assign Y[1] = _09_ |  _10_;
  assign _03_ = _11_ &  B[0];
  assign _04_ = A[0] &  _12_;
  assign Y[0] = _03_ |  _04_;
  assign _05_ = _13_ &  B[1];
  assign _06_ = A[1] &  _14_;
  assign _2_[1] = _05_ |  _06_;
  assign _07_ = _15_ &  _1_[0];
  assign _08_ = _2_[1] &  _16_;
  assign _0_[1] = _07_ |  _08_;
  assign _1_[0] = A[0] &  B[0];
endmodule
