/* Generated by Yosys 0.8 (git sha1 UNKNOWN, clang 10.0.0 -fPIC -Os) */

(* src = "ALU.sv:21" *)
module ALU(a, b, ctrl, zero, result);
  (* src = "ALU.sv:31" *)
  wire [3:0] _00_;
  wire [1:0] _01_;
  wire _02_;
  (* src = "ALU.sv:32" *)
  wire [3:0] _03_;
  (* src = "ALU.sv:30|<techmap.v>:432" *)
  wire [7:0] _04_;
  wire _05_;
  (* src = "ALU.sv:22" *)
  input [3:0] a;
  (* src = "ALU.sv:23" *)
  input [3:0] b;
  (* src = "ALU.sv:24" *)
  input ctrl;
  (* src = "ALU.sv:26" *)
  output [3:0] result;
  (* src = "ALU.sv:25" *)
  output zero;
  assign result[2] = _04_[2] |(* src = "ALU.sv:30|<techmap.v>:441" *)  _04_[6];
  assign result[3] = _04_[3] |(* src = "ALU.sv:30|<techmap.v>:441" *)  _04_[7];
  assign result[1] = _04_[1] |(* src = "ALU.sv:30|<techmap.v>:441" *)  _04_[5];
  assign result[0] = _04_[0] |(* src = "ALU.sv:30|<techmap.v>:441" *)  _04_[4];
  assign _01_[0] = result[0] |(* src = "ALU.sv:36" *)  result[1];
  assign _01_[1] = result[2] |(* src = "ALU.sv:36" *)  result[3];
  assign _02_ = _01_[0] |(* src = "ALU.sv:36" *)  _01_[1];
  assign zero = ~(* src = "ALU.sv:36" *) _02_;
  assign _05_ = ~(* src = "ALU.sv:30" *) ctrl;
  assign _00_[0] = a[0] &(* src = "ALU.sv:31" *)  b[0];
  assign _00_[1] = a[1] &(* src = "ALU.sv:31" *)  b[1];
  assign _00_[2] = a[2] &(* src = "ALU.sv:31" *)  b[2];
  assign _00_[3] = a[3] &(* src = "ALU.sv:31" *)  b[3];
  assign _03_[0] = a[0] |(* src = "ALU.sv:32" *)  b[0];
  assign _03_[1] = a[1] |(* src = "ALU.sv:32" *)  b[1];
  assign _03_[2] = a[2] |(* src = "ALU.sv:32" *)  b[2];
  assign _03_[3] = a[3] |(* src = "ALU.sv:32" *)  b[3];
  assign _04_[4] = _00_[0] &(* src = "ALU.sv:30|<techmap.v>:434" *)  _05_;
  assign _04_[5] = _00_[1] &(* src = "ALU.sv:30|<techmap.v>:434" *)  _05_;
  assign _04_[6] = _00_[2] &(* src = "ALU.sv:30|<techmap.v>:434" *)  _05_;
  assign _04_[7] = _00_[3] &(* src = "ALU.sv:30|<techmap.v>:434" *)  _05_;
  assign _04_[0] = _03_[0] &(* src = "ALU.sv:30|<techmap.v>:434" *)  ctrl;
  assign _04_[1] = _03_[1] &(* src = "ALU.sv:30|<techmap.v>:434" *)  ctrl;
  assign _04_[2] = _03_[2] &(* src = "ALU.sv:30|<techmap.v>:434" *)  ctrl;
  assign _04_[3] = _03_[3] &(* src = "ALU.sv:30|<techmap.v>:434" *)  ctrl;
endmodule
